
services:
  auction:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
 
    networks:
      - localNetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongodb:27017
    networks:
      - localNetwork

  auction_test:
    build:
      dockerfile: Dockerfile_test
      context: .
    environment:
      - BASE_URL=http://auction:8080
    networks:
      - localNetwork


volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge